.TH "POSTING IMPORT" "1" "2026-01-02" "None" "posting import Manual"
.SH NAME
posting\-import \- Import an OpenAPI specification into a...
.SH SYNOPSIS
.B posting import
[OPTIONS] SPEC_PATH
.SH DESCRIPTION
Import an OpenAPI specification into a Posting collection.
.SH OPTIONS
.TP
\fB\-o,\fP \-\-output PATH
Path to save the imported collection
.TP
\fB\-t,\fP \-\-type TEXT
Specify spec type [openapi, postman]
