.TH "POSTING" "1" "2026-01-02" "None" "posting Manual"
.SH NAME
posting \- A TUI for testing HTTP APIs.
.SH SYNOPSIS
.B posting
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
A TUI for testing HTTP APIs.
.SH COMMANDS
.PP
\fBdefault\fP
  .PP
  See \fBposting-default(1)\fP for full documentation on the \fBdefault\fP command.
.PP
\fBlocate\fP
  .PP
  See \fBposting-locate(1)\fP for full documentation on the \fBlocate\fP command.
.PP
\fBimport\fP
  Import an OpenAPI specification into a...
  See \fBposting-import(1)\fP for full documentation on the \fBimport\fP command.
.PP
\fBsponsors\fP
  Show the list of sponsors.
  See \fBposting-sponsors(1)\fP for full documentation on the \fBsponsors\fP command.
